- name: check if mamba is installed
  shell: command -v mamba
  register: mamba_exists
  ignore_errors: True

- name: download miniforge installer
  when: mamba_exists is failed
  become: True
  get_url:
    url: "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh"
    dest: "/tmp/Miniforge3-Linux-x86_64.sh"

- name: run miniforge installer
  when: mamba_exists is failed
  become: True
  shell: "/bin/bash /tmp/Miniforge3-Linux-x86_64.sh -b -p $HOME/miniforge3"
  args:
    creates: "{{ ansible_env.HOME }}/miniforge3/bin/conda"

- name: clean up temporary files
  when: mamba_exists is failed
  become: True
  file:
    path: /tmp/Miniforge3-Linux-x86_64.sh
    state: absent
  ignore_errors: true

- name: set shell configuration file to .zshrc if using zsh
  set_fact:
    shell_config_file: "{{ ansible_env.HOME }}/.zshrc"
  when: is_zsh | default(false)

- name: set shell configuration file to .bashrc if using bash
  set_fact:
    shell_config_file: "{{ ansible_env.HOME }}/.bashrc"
  when: not is_zsh | default(false)

- name: add miniforge3 to path
  lineinfile:
    path: "{{ shell_config_file }}"
    line: 'export PATH="$HOME/miniforge3/bin:$PATH"'
    insertafter: EOF
  when: shell_config_file is defined

- name: update conda
  command: "$HOME/miniforge3/bin/conda update -n base -c defaults conda"
  environment:
    PATH: "$HOME/miniforge3/bin:$PATH"
