[env]
term = "xterm-256color"

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }
size = 12.0
offset = { x = 0, y = 0 }

[terminal.shell]
program = "/usr/bin/tmux"

