- name: upgrade apt packages
  become: true
  apt:
    cache_valid_time: 604800
    state: latest
    upgrade: yes

- name: install apt packages for zsh
  become: true
  apt:
    cache_valid_time: 604800
    state: latest
    name:
      - zsh
      - fzf
      # - cmake 
      # - pkg-config 
      # - libfreetype6-dev 
      # - libfontconfig1-dev 
      # - libxcb-xfixes0-dev 
      # - libxkbcommon-dev 
      # - python3
      # - alacritty

- name: install oh-my-zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    version: master

- name: clone powerlevel10k repository
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k

- name: clone zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: clone zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: clone zsh-bat
  git:
    repo: https://github.com/fdellwing/zsh-bat.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-bat

- name: fzf plugin repo
  git:
    repo: https://github.com/junegunn/fzf
    dest: ~/.fzf

- name: install fzf plugin
  command: ~/.fzf/install --key-bindings --completion --no-update-rc --no-bash --no-fish

- name: install zoxide plugin
  shell: curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh

- name: stow zsh dotfiles
  command: "stow -d $HOME/dotfiles -t ~/ {{ item }}"
  loop:
    - zsh

- name: set shell to zsh
  command: chsh -s /usr/bin/zsh $USER
  become: true

- name: note shell is zsh
  set_fact:
    is_zsh: true
