- name: upgrade apt packages
  become: true
  apt:
    cache_valid_time: 604800
    state: latest
    upgrade: yes

- name: install apt packages for zsh
  become: true
  apt:
    cache_valid_time: 604800
    state: latest
    name:
      - zsh
      - fzf

- name: clone zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.zsh/plug/zsh-autosuggestions

- name: clone zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.zsh/plug/zsh-syntax-highlighting

- name: download starship install script
  get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship_install.sh
    mode: '0755'

- name: run starship install script
  shell: /tmp/starship_install.sh -y
  args:
    creates: /usr/local/bin/starship

- name: download mcfly install script
  get_url:
    url: https://raw.githubusercontent.com/cantino/mcfly/master/ci/install.sh
    dest: /tmp/mcfly_install.sh
    mode: '0755'

- name: run mcfly install script
  command: /tmp/mcfly_install.sh --git cantino/mcfly --force

- name: download zoxide install script
  get_url:
    url: https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh
    dest: /tmp/zoxide_install.sh
    mode: '0755'

- name: run zoxide install script
  shell: /tmp/zoxide_install.sh --bin-dir /usr/local/bin
  args:
    creates: /usr/local/bin/zoxide

- name: stow zsh dotfiles
  command: "stow -d $HOME/dotfiles -t ~/ {{ item }}"
  loop:
    - zsh

- name: set shell to zsh
  command: chsh -s /usr/bin/zsh $USER
  become: true

- name: note shell is zsh
  set_fact:
    is_zsh: true
