- name: check if sdkman is installed
  shell: command -v sdk
  register: sdk_exists
  ignore_errors: True

- name: download installer
  when: sdk_exists is failed
  become: True
  get_url:
    url: https://get.sdkman.io
    dest: /tmp/sdkman.sh
    mode: '0755'
    force: 'yes'

- name: install sdkman
  when: sdk_exists is failed
  become: True
  shell: /tmp/sdkman.sh 

- name: setup sdkman and install java, gradle
  when: sdk_exists is failed
  become: True
  shell: |
    source $HOME/.sdkman/bin/sdkman-init.sh
    sdk install java 17.0.12-oracle
    sdk install gradle
  args:
    executable: /bin/bash
