- name: CAN FAIL - check if sdkman is installed
  shell: command -v sdk >/dev/null 2>&1
  register: sdk_installed
  ignore_errors: yes

- name: display sdkman install state
  debug:
    msg: "sdkman install state: {{ sdk_installed }}"
  when: verbose == true

- name: download installer
  when: sdk_installed is failed
  get_url:
    url: https://get.sdkman.io
    dest: /tmp/sdkman.sh
    mode: '0755'
    force: 'yes'

- name: install sdkman
  when: sdk_installed is failed
  shell: /tmp/sdkman.sh 

- name: setup sdkman and install java, gradle
  when: sdk_installed is failed
  shell: |
    source $HOME/.sdkman/bin/sdkman-init.sh
    sdk install java 17.0.12-oracle
    sdk install gradle
  args:
    executable: /bin/bash
