- name: upgrade apt packages
  become: true
  apt:
    cache_valid_time: 604800
    state: latest
    upgrade: yes

- name: install apt packages for core development
  become: true
  apt:
    cache_valid_time: 604800
    state: latest
    name:
      - sudo
      - stow
      - build-essential
      - make
      - grep
      - file
      - pkg-config
      - libssl-dev
      - libudev-dev
      - tmux
      - htop
      - nvtop
      - curl
      - wget
      - zip
      - unzip
      - rsync
      - ripgrep
      - net-tools
      - tree
      - gpg
      - gpg-agent
      - pinentry-curses
      - gnupg2
      - ca-certificates
      - neofetch
      - dbus-x11

- name: install linux-tools-{{ ansible_kernel }}
  become: true
  apt:
    name: linux-tools-{{ ansible_kernel }}
    state: present
  when: not wsl

- name: stow core dotfiles
  command: "stow -d $HOME/dotfiles -t ~/ {{ item }}"
  loop:
    - tmux
