- name: upgrade apt packages
  become: true
  apt:
    cache_valid_time: 604800
    state: latest
    upgrade: yes

- name: install build dependencies
  become: true
  tags: install
  apt:
    cache_valid_time: 604800
    state: latest
    name:
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
      - build-essential

- name: download installer
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
    dest: /tmp/nvim.tar.gz
    mode: '0755'
    force: 'yes'

- name: remove /opt/nvim 
  file:
    path: /opt/nvim
    state: absent
    force: yes

- name: install nvim to /opt
  unarchive:
    src: /tmp/nvim-linux64.tar.gz
    dest: /opt
    remote_src: yes

- name: install lazy.nvim plugin dependencies
  become: true
  tags: config
  apt:
    cache_valid_time: 604800
    state: latest
    name:
      - ripgrep
      - fd-find
      - xclip

- name: stow neovim dotfiles
  command: "stow -d $HOME/dotfiles -t ~/ {{ item }}"
  loop:
    - neovim
