- name: upgrade apt packages
  become: true
  apt:
    cache_valid_time: 604800
    state: latest
    upgrade: yes

- name: CAN FAIL - check if neovim is installed
  shell: command -v nvim
  register: nvim_exists
  ignore_errors: yes

- name: install build dependencies
  when: nvim_exists is failed
  become: true
  tags: install
  apt:
    cache_valid_time: 604800
    state: latest
    name:
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
      - build-essential

- name: clone neovim source code into /usr/local/src
  when: nvim_exists is failed
  become: true
  tags: install
  git:
    repo: https://github.com/neovim/neovim.git
    dest: /usr/local/src/neovim
    version: stable

- name: build neovim
  when: nvim_exists is failed
  become: true
  tags: install
  make:
    chdir: /usr/local/src/neovim
    target: all
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo

- name: build deb package
  when: nvim_exists is failed
  become: true
  tags: install
  command: cpack -G DEB
  args:
    chdir: /usr/local/src/neovim/build

- name: install neovim deb package
  when: nvim_exists is failed
  become: true
  tags: install
  apt:
    deb: /usr/local/src/neovim/build/nvim-linux64.deb

- name: install lazy.nvim plugin dependencies
  become: true
  tags: config
  apt:
    cache_valid_time: 604800
    state: latest
    name:
      - ripgrep
      - fd-find
      - xclip

- name: stow neovim dotfiles
  command: "stow -d $HOME/dotfiles -t ~/ {{ item }}"
  loop:
    - neovim
