- name: Check if Rust is installed
  command: rustc --version
  register: rustc_check
  ignore_errors: yes

- name: Set fact if Rust is installed
  set_fact:
    rust_installed: "{{ rustc_check.rc == 0 }}"

- name: download installer
  when: not rust_installed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: install rust and cargo
  when: not rust_installed
  shell: /tmp/sh.rustup.rs -y

- name: set shell configuration file to .zshrc if using zsh
  set_fact:
    shell_config_file: "{{ ansible_env.HOME }}/.zshrc"
  when: is_zsh | default(false)

- name: set shell configuration file to .bashrc if using bash
  set_fact:
    shell_config_file: "{{ ansible_env.HOME }}/.bashrc"
  when: not is_zsh | default(false)

- name: add rust to path
  lineinfile:
    path: "{{ shell_config_file }}"
    line: '. "$HOME/.cargo/env"'
    insertafter: EOF
  when: shell_config_file is defined
