- name: check if cargo is present
  shell: command -v cargo
  register: rust_installed
  ignore_errors: yes

- name: download installer
  when: rust_installed is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: install rust and cargo
  when: rust_installed is failed
  shell: /tmp/sh.rustup.rs -y

- name: set shell configuration file based on user's shell
  set_fact:
    shell_config_file: "{{ ansible_env.HOME }}/.bashrc"
  when: ansible_env.SHELL.endswith('bash')

- name: set shell configuration file to .zshrc if using zsh
  set_fact:
    shell_config_file: "{{ ansible_env.HOME }}/.zshrc"
  when: ansible_env.SHELL.endswith('zsh')

- name: add rust to path
  lineinfile:
    path: "{{ shell_config_file }}"
    line: '. "$HOME/.cargo/env"'
    insertafter: EOF
  when: shell_config_file is defined
