- name: install cargo packages
  shell: |
    . "$HOME/.cargo/env"
    cargo install {{ item }}
  args:
    executable: /bin/bash
  loop:
    - just
    - typst-cli
    - procs
    - bottom

- name: install clis
  become: true
  apt:
    cache_valid_time: 604800
    state: latest
    name:
      - lsd
      - bat
