- name: download signal signing key
  get_url:
    url: https://updates.signal.org/desktop/apt/keys.asc
    dest: /tmp/signal-keys.asc

- name: convert signal signing key
  command: "gpg --dearmor -o /tmp/signal-desktop-keyring.gpg /tmp/signal-keys.asc"

- name: move gpg key to keyrings directory
  copy:
    src: /tmp/signal-desktop-keyring.gpg
    dest: /usr/share/keyrings/signal-desktop-keyring.gpg
    remote_src: yes

- name: add signal repo
  copy:
    dest: /etc/apt/sources.list.d/signal-xenial.list
    content: |
      deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main

- name: upgrade apt packages
  become: true
  apt:
    cache_valid_time: 604800
    state: latest
    upgrade: yes

- name: install tools
  apt:
    cache_valid_time: 604800
    state: latest
    name:
      - gnucash
      - libdbd-sqlite3
      - libdbd-mysql
      - libdbd-pgsql
      - encfs
      - signal-desktop
      - alacritty
      - gparted
      - thunderbird
      - wireshark
      - gnome-tweaks
      - evolution
      - gnome-shell-extension-manager
      - adb
      - sublime-music

- name: stow alacritty dotfiles
  command: "stow -d $HOME/dotfiles -t ~/ {{ item }}"
  loop:
    - alacritty

- name: dconf load gnucash
  shell: dconf load /org/gnucash/ < $HOME/dotfiles/gnucash/gnucash.dconf

- name: check if snap is installed
  apt:
    name: snapd
    state: present
  register: snapd_installed
  ignore_errors: true

- name: check snapd is running
  service:
    name: snapd
    state: started
    enabled: yes
  when: snapd_installed is succeeded

- name: install snaps
  when: snapd_installed is succeeded
  snap:
    name: "{{ item }}"
    state: present
  loop:
    - slack
    - discord
    - nordpass
    - localsend
    - scrcpy
