- name: ensure the keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: install wget if it's not already installed
  apt:
    name: wget
    state: present

- name: remove firefox snap
  command: snap remove firefox

- name: get mozilla apt key
  shell: /bin/bash -c 'wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null'

- name: add mozilla apt repository
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main
    filename: mozilla
    state: present

- name: set mozilla repo priority
  copy:
    dest: /etc/apt/preferences.d/mozilla
    content: |
      Package: *
      Pin: origin packages.mozilla.org
      Pin-Priority: 1000
    mode: '0644'

- name: update package index
  apt:
    update_cache: yes

- name: install firefox
  apt:
    name: firefox
    state: present
