# ~/.config/starship.toml
# Author: @edurso

format = "$all"
add_newline = false

[battery]
disabled = true

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[✘](bold red)"

[cmd_duration]
disabled = true

[directory]
truncate_to_repo = true
style = "bold purple"
truncation_length = 8
format = "[$path]($style)[$read_only]($read_only_style) "
read_only = "🔒"
read_only_style = "bold purple"

[git_branch]
style = "bold blue"
symbol = "-b "
format = "[$symbol$branch(:$remote_branch)]($style)"

[git_commit]
disabled = true

[git_state]
disabled = true

[git_metrics]
disabled = true

[git_status]
format = "([$all_status$ahead_behind]($style) ) "
conflicted = "conflicts"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
deleted = "✘"
renamed = "»"
style = "bold red"
ignore_submodules = false

[hostname]
ssh_only = false
format = "@[$hostname]($style):"

[jobs]
symbol = "✦"
style = "bold yellow"

[username]
show_always = true
style_root = "bold yellow"
style_user = "bold yellow"
format = "[$user]($style)"

[c]
format = "[$symbol($version(-$name) )]($style)"

[cmake]
format = "[$symbol($version )]($style)"

[cobol]
format = "[$symbol($version )]($style)"

[conda]
format = "[$symbol$environment]($style)"

[crystal]
format = "[$symbol($version )]($style)"

[dart]
format = "[$symbol($version )]($style)"

[docker_context]
format = "[$symbol$context]($style) "

[dotnet]
format = "[$symbol($version )(🎯 $tfm )]($style)"

[golang]
format = "[$symbol($version )]($style)"

[java]
format = "[$symbol($version )]($style)"

[julia]
format = "[$symbol($version )]($style)"

[kotlin]
format = "[$symbol($version )]($style)"

[lua]
format = "[$symbol($version )]($style)"

[nodejs]
format = "[$symbol($version )]($style)"

[perl]
format = "[$symbol($version )]($style)"

[php]
format = "[$symbol($version )]($style)"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rlang]
format = "[$symbol($version )]($style)"

[ruby]
format = "[$symbol($version )]($style)"

[rust]
format = "[$symbol($version )]($style)"

[scala]
format = "[$symbol($version )]($style)"

[swift]
format = "[$symbol($version )]($style)"

