add_newline = false

[character]
symbol = ">"
error_symbol = "x"
use_symbol_for_status = true
style_success = "bold green"
style_failure = "bold red"
vicmd_symbol = "<"

[cmd_duration]
disabled = true

[directory]
truncate_to_repo = true
style = "bold purple"
truncation_length = 8

[battery]
disabled = true

[git_branch]
symbol = "-b "
style = "bold blue"

[git_commit]
disabled = true

[git_status]
conflicted = "conflicts"
ahead = "^"
behind = "v"
diverged = "diverged"
deleted = "rm"
renamed = "#"

[hostname]
ssh_only = false
prefix = "@"

[java]
symbol = "java "

[jobs]
symbol = "+"
style = "bold yellow"

[nodejs]
symbol = "js "

[ruby]
symbol = "rb "

[package]
symbol = "pkg"

[python]
symbol = "py "
pyenv_version_name = false

[username]
show_always = true
style_root = "bold yellow"
style_user = "bold yellow"

