# ~/.config/starship.toml
# Author: @edurso

add_newline = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[X](bold red)"

[cmd_duration]
disabled = true

[directory]
truncate_to_repo = true
style = "bold purple"
truncation_length = 8

[git_branch]
symbol = "-b "
style = "bold blue"

[git_commit]
disabled = true

[git_status]
conflicted = "conflicts"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
deleted = "✘"
renamed = "»"

[hostname]
ssh_only = false
format = "@[$hostname]($style) in "

[jobs]
symbol = "+"
style = "bold yellow"

[username]
show_always = true
style_root = "bold yellow"
style_user = "bold yellow"
format = "[$user]($style)"
